# Generated by Django 4.2.7 on 2023-11-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rc_number', models.CharField(max_length=20, unique=True)),
                ('additional_data', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
